name: common
description: common
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: 4.0.6
  flutter_svg: 1.1.2
  equatable: 2.0.3
  url_launcher: 6.1.2
  json_annotation: 4.6.0
  flutter_modular: 5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.2.0
  modular_test: 2.0.0
  mobx_codegen: 2.0.7
  mockito: 5.3.0
  json_serializable: 6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon_top_bar.png
    - assets/icons/icon_bottom_bar.png
